title: UTC
description: >-
  https://app.snapchat.com/dmd/memories?uid=85206279-be6c-4e1f-a7e5-4e9e2ca6a452&sid=EBF6D64B-FB51-4DAF-8355-2A1C7709CE86&mid=EBF6D64B-FB51-4DAF-8355-2A1C7709CE86&ts=1595150967883&proxy=true&sig=8e5363432618093335fba24dc55d67bca057f0f4e9eb337697a06b51056c0f
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
